#!/usr/bin/env python3
"""Generate the skill lookup table from the pinned upstream CSV."""
import csv
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
ANCHORS = {
    'SDK Integration': 'startup', 'Lifecycle API': 'startup',
    'Sound Management': 'sound-and-lifecycle', 'Ads — Interstitial': 'ads',
    'Ads — Rewarded': 'ads', 'Cloud Saves': 'saves', 'In-App Purchases': 'purchases',
    'Localization (I18N)': 'localization', 'UX & Mobile': 'browser-and-mobile',
    'Common Rejections': 'startup', 'Dangerous Patterns': 'dangerous-patterns',
    'Archive': 'archive', 'Quality': 'quality-and-controls', 'Leaderboard': 'leaderboards',
    'Timing Verification': 'timing', 'Visual Overflow (п.1.10.1)': 'runtime-visual-and-console-checks',
    'Language Check (Runtime)': 'localization', 'Scroll/Refresh (Runtime)': 'browser-and-mobile',
    'Ad Context (Runtime)': 'ads', 'Ad Context (v2.4 Runtime)': 'ads',
    'Runtime Detection': 'runtime-visual-and-console-checks',
}
def render():
    with (ROOT/'vendor/yandex-games-debug-checker/checks.csv').open(newline='') as f:
        rows = list(csv.DictReader(f))
    out = ['# Complete check catalog', '',
           f'{len(rows)} rows from the pinned upstream CSV. Generated by `python3 scripts/generate_catalog.py`.',
           'Numbers identify rows in this snapshot, not stable upstream API IDs. Titles/classifications are preserved;',
           'they can differ from dynamically inferred panel badges. REQ is a rule association, not proof of a violation.',
           'Use [the runbook](debug-checker.md) to execute and interpret checks, and [the fix guide](check-remediation.md) for remedies.', '',
           '| # | Section | Mode | Exact check | Clause | Class | Fix guide |',
           '|---:|---|---|---|---|---|---|']
    for i, row in enumerate(rows, 1):
        anchor = ANCHORS[row['section']]
        # Route cross-cutting static checks to the relevant behavior.
        name = row['check']
        if row['section'] in ('Common Rejections', 'Quality'):
            if any(x in name for x in ('I18N', 'Language', 'language')): anchor = 'localization'
            elif any(x in name for x in ('ads', 'ad ', 'Ad ', 'ad blocks', 'ad networks')): anchor = 'ads'
            elif any(x in name for x in ('Scroll', 'Swipe', 'Selection')): anchor = 'browser-and-mobile'
            elif any(x in name for x in ('ready()', 'Ввод')): anchor = 'startup'
        vals = [str(i),row['section'],row['type'],name,row['requirement'] or '—',row['classification'],f'[Resolve](check-remediation.md#{anchor})']
        out.append('| ' + ' | '.join(v.replace('|', '\\|') for v in vals) + ' |')
    return '\n'.join(out)+'\n'
if __name__ == '__main__':
    (ROOT/'references/check-catalog.md').write_text(render())
